# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesage',
            name='ot_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 11, 26, 53, 217905, tzinfo=utc)),
        ),
    ]
