# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gb', '0002_mesage_ot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesage',
            name='ot_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
